version: '2'
services:
  redis:
    image: 'redis:alpine'
    # networks:
    #   - redis
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    # networks:
    #   - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: main-admin
      MONGO_INITDB_ROOT_PASSWORD: main-admin
      MONGO_INITDB_DATABASE: school-portal-system
    ports:
      - '27017:27017'

  nestjs-api:
    build:
      context: .
      target: install-dependencies
    command: npm run start:dev
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env.stage.dev
    ports:
      - "3000:3000"
    depends_on:
      - redis
    # networks:
    #   - redis

  # networks:
  #   postgres:
  #     driver: bridge
# ...

